# URLs and checksums for the dicom3tools binary archives that this project wraps.
#
# This file is the seam between the two halves of the project: the build workflows in
# ImagingDataCommons/dicom3tools compile per-platform archives and attach them to a GitHub
# release, and this file pins exactly which ones a wheel is built from. The wheel layer never
# knows or cares who produced them -- so if the archives ever move (upstream dclunie.com, a
# different repository), only the variables below change and nothing else in the repo moves.
#
# Regenerate the auto-generated section with:
#
#   python scripts/update_dicom3tools_urls.py --tag <tag>
#
# One cache variable allows repointing a build without editing this file:
#
#   -DDICOM3TOOLS_BINARIES_BASE_URL=file:///path/to/dir   # archives from a local dir
#
# Note that the checksums are always enforced. To build against a different set of archives,
# run the update script rather than overriding the hash check.

# These two are rewritten by the update script along with the checksums below, and must stay
# consistent with them: they are what turns a pinned filename into a URL. The tag is an
# immutable release, never a rolling pointer such as "latest".
#
# The tag matters more here than it does in the projects this one is modelled on. The
# dicom3tools assets are named identically in every release -- there is no version or commit in
# the filename -- so a stale tag does not 404, it downloads a real archive from the wrong
# release and fails the checksum. The tag is the version.
set(DICOM3TOOLS_BINARIES_REPO "ImagingDataCommons/dicom3tools"
  CACHE STRING "GitHub repository hosting the dicom3tools binary archives")
set(DICOM3TOOLS_BINARIES_TAG "dicom3tools.20260901072548.post4"
  CACHE STRING "Release tag hosting the dicom3tools binary archives")
set(DICOM3TOOLS_BINARIES_BASE_URL ""
  CACHE STRING "Override the base URL the archives are fetched from (default: the GitHub release)")

# The section below is auto-generated by scripts/update_dicom3tools_urls.py
# Do not edit this section directly.

set(dicom3tools_snapshot "20260901072548")
set(dicom3tools_version  "20260901")

set(linux_x86_64_filename   "dicom3tools-linux-x86_64.tar.gz")
set(linux_x86_64_sha256     "bb91089b90b98c9ff1733fb12e962eea683215933224ef0ead1566601b23d9fe")

set(linux_aarch64_filename  "dicom3tools-linux-aarch64.tar.gz")
set(linux_aarch64_sha256    "8357e346a82065dec1b7932577f63aa8edee7786ffe37adae7664eedd85ab5a8")

set(macos_arm64_filename    "dicom3tools-macos-arm64.tar.gz")
set(macos_arm64_sha256      "6e3a126cff472fa96e1d6af6e6d30b70e477d0e5e4d2581f4a1a7036bec7a048")

set(macos_x86_64_filename   "dicom3tools-macos-x86_64.tar.gz")
set(macos_x86_64_sha256     "e83dbcb000b3e558a33cfc35f07822cb1208d7195d7a8e6c696dfcdc9ed247fb")

set(win64_filename          "dicom3tools-windows-x86_64.zip")
set(win64_sha256            "6b327bc66dcd46f37eef11edde32b40fa7b84336f764f3e02e111ebe1472717f")

# The section above is auto-generated by scripts/update_dicom3tools_urls.py
# Do not edit this section directly.

#
# Pick the archive for the machine the wheel is being built for.
#
# There is no cross-compilation anywhere in this project: the archives are prebuilt
# single-architecture binaries that cannot be retargeted at wheel-build time, so each wheel is
# built on a runner of its own architecture (see .github/workflows/cd.yml) and the choice is
# made from the host processor.
#
if(APPLE)
  if(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
    set(archive "macos_arm64")
  else()
    set(archive "macos_x86_64")
  endif()
elseif(WIN32)
  # The Windows package is built under Cygwin as 64-bit x86 only. An ARM64 Windows machine can
  # run it through emulation, but the wheel would then be tagged win_arm64 and claim otherwise.
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(AMD64|x86_64)$")
    set(archive "win64")
  else()
    message(FATAL_ERROR
      "No dicom3tools archive is published for this Windows architecture "
      "(CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}). Only 64-bit x86 is supported.")
  endif()
else()
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$")
    set(archive "linux_x86_64")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
    set(archive "linux_aarch64")
  else()
    message(FATAL_ERROR
      "No dicom3tools archive is published for this Linux architecture "
      "(CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}). Only x86_64 and aarch64 are built.")
  endif()
endif()

if(NOT DEFINED "${archive}_filename")
  message(FATAL_ERROR "Failed to determine which archive to download: '${archive}_filename' is not defined")
endif()

if(NOT DEFINED "${archive}_sha256")
  message(FATAL_ERROR "Could you make sure variable '${archive}_sha256' is defined ?")
endif()

set(dicom3tools_archive_filename "${${archive}_filename}")
set(dicom3tools_archive_sha256 "${${archive}_sha256}")

if(DICOM3TOOLS_BINARIES_BASE_URL)
  set(_base_url "${DICOM3TOOLS_BINARIES_BASE_URL}")
else()
  set(_base_url
    "https://github.com/${DICOM3TOOLS_BINARIES_REPO}/releases/download/${DICOM3TOOLS_BINARIES_TAG}")
endif()

set(dicom3tools_archive_url "${_base_url}/${dicom3tools_archive_filename}")
