#!/usr/bin/env python3
"""
Regenerate the auto-generated section of ``dicom3toolsUrls.cmake``.

Reads the assets attached to a dicom3tools GitHub release, downloads each platform archive,
computes its SHA256, and rewrites the pinned filenames and checksums in place. Run this
whenever the wheels should be built from a new set of binaries:

    python scripts/update_dicom3tools_urls.py \
        --repo ImagingDataCommons/dicom3tools --tag dicom3tools.20260901072548.post3

``--repo``/``--tag`` name the release hosting the archives, cut by the build workflows in the
dicom3tools repository. Both are written into dicom3toolsUrls.cmake next to the checksums, so
the file always records where the bytes it pins came from.

Unlike plastimatch's archives, the dicom3tools assets have constant filenames across releases
(``dicom3tools-linux-x86_64.tar.gz`` and friends). The release tag is therefore the only thing
that distinguishes one release's assets from another's, which is why it is pinned in the same
file and rewritten here rather than left to be updated by hand. The upstream version is read
off the tag for the same reason: no asset name carries it.

Set ``GITHUB_TOKEN`` in the environment to read a private repository or to avoid the
unauthenticated API rate limit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from pathlib import Path
from urllib.request import Request, urlopen

# Maps the CMake variable prefix to the exact asset name for that platform. Exact rather than
# a substring match, because "dicom3tools-macos-x86_64.tar.gz" is a substring-shaped trap:
# "-macos-" alone also matches the universal archive, which is deliberately not pinned. The
# wheels are per-architecture, so the thin archives give the same result at half the size.
PLATFORM_ASSETS = {
    "linux_x86_64": "dicom3tools-linux-x86_64.tar.gz",
    "linux_aarch64": "dicom3tools-linux-aarch64.tar.gz",
    "macos_arm64": "dicom3tools-macos-arm64.tar.gz",
    "macos_x86_64": "dicom3tools-macos-x86_64.tar.gz",
    "win64": "dicom3tools-windows-x86_64.zip",
}

# Release tags look like dicom3tools.20260901072548 or dicom3tools.20260901072548.post3, where
# the 14 digits are the timestamp of the upstream snapshot (VERSION.txt records the same one as
# dicom3tools_1.00.snapshot.20260901072548.tar.bz2).
TAG_RE = re.compile(r"^dicom3tools\.(?P<snapshot>\d{14})(?:\.post\d+)?$")

BLOCK_RE = re.compile(
    r"# The section below is auto-generated by scripts/update_dicom3tools_urls\.py\n"
    r"# Do not edit this section directly\.\n"
    r"[\s\S]+?"
    r"# The section above is auto-generated by scripts/update_dicom3tools_urls\.py\n"
    r"# Do not edit this section directly\.\n"
)

# DICOM3TOOLS_BINARIES_REPO and _TAG live outside the auto-generated block, but they are half of
# the pin: the block names files and checksums, and these two turn a filename into a URL.
# Rewriting only the block leaves the file self-consistent-looking and completely broken --
# every checksum from the new release, every download from the old one. So they are rewritten
# too. This matters more here than in the plastimatch original, where a stale tag at least
# produced 404s: the dicom3tools filenames are identical in every release, so a stale tag
# downloads real archives that simply are not the ones the checksums describe.
REPO_RE = re.compile(r'(?m)^(set\(DICOM3TOOLS_BINARIES_REPO ")[^"]*(")')
TAG_ASSIGN_RE = re.compile(r'(?m)^(set\(DICOM3TOOLS_BINARIES_TAG ")[^"]*(")')

CHUNK = 1 << 20


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--repo",
        default="ImagingDataCommons/dicom3tools",
        help="owner/name of the GitHub repository hosting the archives",
    )
    parser.add_argument("--tag", required=True, help="release tag hosting the archives")
    parser.add_argument(
        "--cmake-file",
        type=Path,
        default=Path(__file__).parents[1] / "dicom3toolsUrls.cmake",
        help="path to dicom3toolsUrls.cmake",
    )
    return parser.parse_args()


def _request(url: str, accept: str) -> Request:
    headers = {"Accept": accept, "User-Agent": "update_dicom3tools_urls"}
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return Request(url, headers=headers)


def fetch_release(repo: str, tag: str) -> dict:
    url = f"https://api.github.com/repos/{repo}/releases/tags/{tag}"
    with urlopen(_request(url, "application/vnd.github+json")) as response:
        return json.load(response)


def sha256_of(asset: dict) -> str:
    """Stream the asset and return its SHA256, without holding it all in memory."""
    digest = hashlib.sha256()
    request = _request(asset["url"], "application/octet-stream")
    with urlopen(request) as response:
        while chunk := response.read(CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


def version_from_tag(tag: str) -> tuple[str, str]:
    """Return (snapshot, wheel version) for a dicom3tools release tag.

    The wheel version is upstream's 1.00 followed by the snapshot date: 1.0.20260901. See the
    Versioning section of the README for why the date rather than a serial number, and why the
    time of day is dropped.
    """
    match = TAG_RE.match(tag)
    if match is None:
        msg = (
            f"Tag '{tag}' is not a dicom3tools release tag. Expected "
            "dicom3tools.<14-digit snapshot>[.postN], e.g. dicom3tools.20260901072548.post3."
        )
        raise ValueError(msg)
    snapshot = match.group("snapshot")
    return snapshot, f"1.0.{snapshot[:8]}"


def generate_block(assets: list[dict], tag: str) -> str:
    by_name = {asset["name"]: asset for asset in assets}
    missing = [name for name in PLATFORM_ASSETS.values() if name not in by_name]
    if missing:
        msg = (
            f"Release '{tag}' is missing {missing}. Available: {sorted(by_name)}. "
            "A release is only usable here once all of the platform build workflows have "
            "finished and attached their archives."
        )
        raise ValueError(msg)

    snapshot, version = version_from_tag(tag)

    lines = [
        "# The section below is auto-generated by scripts/update_dicom3tools_urls.py",
        "# Do not edit this section directly.",
        "",
        f'set(dicom3tools_snapshot "{snapshot}")',
        f'set(dicom3tools_version  "{version}")',
        "",
    ]

    for key, name in PLATFORM_ASSETS.items():
        checksum = sha256_of(by_name[name])
        print(f"{checksum}  {name}")
        lines.append(f"set({key}_filename".ljust(28) + f'"{name}")')
        lines.append(f"set({key}_sha256".ljust(28) + f'"{checksum}")')
        lines.append("")

    lines += [
        "# The section above is auto-generated by scripts/update_dicom3tools_urls.py",
        "# Do not edit this section directly.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    args = parse_args()

    release = fetch_release(args.repo, args.tag)
    assets = release.get("assets", [])
    if not assets:
        msg = f"Release '{args.tag}' in {args.repo} has no assets"
        raise ValueError(msg)

    block = generate_block(assets, args.tag)

    text = args.cmake_file.read_text(encoding="utf-8")
    if not BLOCK_RE.search(text):
        msg = f"Could not find the auto-generated block in {args.cmake_file}"
        raise ValueError(msg)

    text = BLOCK_RE.sub(block, text)

    for name, pattern, value in (
        ("DICOM3TOOLS_BINARIES_REPO", REPO_RE, args.repo),
        ("DICOM3TOOLS_BINARIES_TAG", TAG_ASSIGN_RE, args.tag),
    ):
        text, count = pattern.subn(lambda m, v=value: m.group(1) + v + m.group(2), text)
        if count != 1:
            msg = (
                f"Expected exactly one {name} assignment in {args.cmake_file}, found {count}. "
                f"The checksums would then point at assets fetched from a different release."
            )
            raise ValueError(msg)

    args.cmake_file.write_text(text, encoding="utf-8")
    print(f"Updated {args.cmake_file} from {args.repo}@{args.tag}")


if __name__ == "__main__":
    main()
